### ISSUE TITLE
Questions about the Dataset

### ISSUE THREAD

**Issue by starsay** [theonegis/edcstfn#1]

**Comment by FZfangzheng** [comment]
作者您好，我尝试使用您的代码进行训练，但是效果似乎不是很好。我采用的参数是run.py文件开头给出的建议参数，不同之处在于根据我训练集图片大小改动了切块的大小。自编码器训练了30个epoch，训练结果来看loss长时间稳定E-4，训练准确性长时间稳定E-6。验证结果来看，RMSE=6~10，ERGAS=3.4，SAM=1.3，这些似乎比论文中提到的大不少。我尝试修改学习率，做归一化处理，但是没有好转。所以我才向作者请教，作者若有空能给予一些帮助？谢谢

**Comment by starsay** [comment]
> Thank you for useful sharing.And I have questions about the pictures used in this model.What image formats are they in the program, and where could I get available data sets.

**Comment by FZfangzheng** [comment]
The data set I obtained from the paper "Spatio-Temporal Fusion for Remote Sensing Data: An overview and New Benchmark", I hope this can help you. I do n’t know if it ’s because of the data set that the result of my run is quite different from the paper. If you can use this data set to run well, please let me know in the first time, thank you




------------------ 原始邮件 ------------------
发件人:&nbsp;"starsay"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 中午11:00
收件人:&nbsp;"theonegis/edcstfn"<edcstfn@noreply.github.com&gt;;
抄送:&nbsp;"方政"<774380232@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [theonegis/edcstfn] Questions about the Dataset (#1)





  
Thank you for useful sharing.And I have questions about the pictures used in this model.What image formats are they in the program, and where could I get available data sets.
